### ISSUE TITLE
Examples of multiple choice Fields and Choices

### ISSUE THREAD

**Issue by GraphiteWingedBird** [jasoth/Utility.PS#1]
Alright - so this definitely isn't an issue, but since you have so many great examples, I figured I'd let you know another example that might be helpful to truly make your `Write-HostPrompt` the full deal if anyone else comes across it and decides to use it.

Some examples are here: https://github.com/PowerShell/vscode-powershell/blob/master/examples/PromptExamples.ps1

What I think is most helpful, and notably missing from your current examples, are using arrays to allow multiple fields. The example in the link above is basically multiple choice and seems like an overload, but isn't truly. Below is also an overengineered example that makes creating a `ChoicePrompt` somewhat easier - although applications would certainly be limited.

```pwsh
function Create-ChoicePrompt{
[System.Management.Automation.Host.FieldDescription]$Title = "Title"
[System.Management.Automation.Host.FieldDescription]$Message = "Message"
[System.Management.Automation.Host.FieldDescription]$Choices = "Choices"
[System.Management.Automation.Host.FieldDescription]$DefaultChoice = "DefaultChoice"
$Choices.SetParameterType([string[]])
$DefaultChoice.SetParameterType([int])
$DefaultChoice.DefaultValue = 0
[System.Management.Automation.Host.FieldDescription[]]$Fields = $Title, $Message, $Choices, $DefaultChoice
$Host.UI.Prompt("Choice Prompt Helper", "Enter the items below to generate arguments for a user choice",$Fields)
}
$HostPromptArguments = Create-ChoicePrompt
Write-HostPrompt @HostPromptArguments
```

The most salient detail that might be worth adding an example is that you can use `.SetParameterType()` to use arrays as well as single data types. So in your `[datetime]` example, if you wanted to get multiple dates/times, you could use `$DateTimeField.SetParameterType([datetime[]])`.

**Comment by jazuntee** [comment]
Thanks for the suggestions. I have updated my example to use an int array field to show it working with arrays as well.
